<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>io.github.susimsek</groupId>
	<artifactId>spring-grpc-samples</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-grpc-samples</name>
	<description>Spring gRPC server sample</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>25</java.version>
		<lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
		<org.mapstruct.version>1.6.3</org.mapstruct.version>
		<jacoco.version>0.8.14</jacoco.version>
		<protovalidate.version>0.14.0</protovalidate.version>
		<spotless-maven-plugin.version>3.9.0</spotless-maven-plugin.version>
		<google-java-format.version>1.35.0</google-java-format.version>
		<maven-checkstyle-plugin.version>3.6.0</maven-checkstyle-plugin.version>
		<checkstyle.version>13.9.0</checkstyle.version>
		<properties-maven-plugin.version>1.2.1</properties-maven-plugin.version>
		<sonar-maven-plugin.version>5.7.0.6970</sonar-maven-plugin.version>
		<jib-maven-plugin.version>3.5.2</jib-maven-plugin.version>
		<jib-spring-boot-extension-maven.version>0.1.0</jib-spring-boot-extension-maven.version>
		<jib-native-image-extension-maven.version>0.1.0</jib-native-image-extension-maven.version>
		<jib-maven-plugin.image>eclipse-temurin:25-jre-alpine</jib-maven-plugin.image>
		<jib-maven-plugin.os>linux</jib-maven-plugin.os>
		<jib-maven-plugin.architecture>arm64</jib-maven-plugin.architecture>
		<native-image-name>native-executable</native-image-name>
		<start-class>io.github.susimsek.springgrpcsamples.SpringGrpcSamplesApplication</start-class>
	</properties>
	<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-grpc-server</artifactId>
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-liquibase</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
		</dependency>
		<dependency>
			<groupId>build.buf</groupId>
			<artifactId>protovalidate</artifactId>
			<version>${protovalidate.version}</version>
		</dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-grpc-server-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>io.github.ascopes</groupId>
				<artifactId>protobuf-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.diffplug.spotless</groupId>
				<artifactId>spotless-maven-plugin</artifactId>
				<version>${spotless-maven-plugin.version}</version>
				<configuration>
					<java>
						<googleJavaFormat>
							<version>${google-java-format.version}</version>
							<style>AOSP</style>
							<reflowLongStrings>true</reflowLongStrings>
						</googleJavaFormat>
						<removeUnusedImports/>
					</java>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>${maven-checkstyle-plugin.version}</version>
				<dependencies>
					<dependency>
						<groupId>com.puppycrawl.tools</groupId>
						<artifactId>checkstyle</artifactId>
						<version>${checkstyle.version}</version>
					</dependency>
				</dependencies>
				<configuration>
					<configLocation>checkstyle.xml</configLocation>
					<suppressionsLocation>checkstyle-suppressions.xml</suppressionsLocation>
					<consoleOutput>true</consoleOutput>
					<outputFile>${project.build.directory}/checkstyle-result.xml</outputFile>
					<outputFileFormat>xml</outputFileFormat>
					<failsOnError>true</failsOnError>
					<linkXRef>false</linkXRef>
					<excludes>.git/**/*,target/**/*</excludes>
					<sourceDirectories>./</sourceDirectories>
				</configuration>
				<executions>
					<execution>
						<id>checkstyle</id>
						<phase>validate</phase>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>${lombok-mapstruct-binding.version}</version>
						</path>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${jacoco.version}</version>
				<configuration>
					<excludes>
						<exclude>io/github/susimsek/springgrpcsamples/proto/**</exclude>
						<exclude>io/github/susimsek/springgrpcsamples/mapper/*MapperImpl.class</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<useManifestOnlyJar>false</useManifestOnlyJar>
					<runOrder>alphabetical</runOrder>
					<excludes>
						<exclude>**/*IT*</exclude>
						<exclude>**/*IntTest*</exclude>
					</excludes>
					</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
			</plugin>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>${jib-maven-plugin.version}</version>
				<configuration>
					<from>
						<image>${jib-maven-plugin.image}</image>
						<platforms>
							<platform>
								<architecture>${jib-maven-plugin.architecture}</architecture>
								<os>${jib-maven-plugin.os}</os>
							</platform>
						</platforms>
					</from>
					<to>
						<image>${project.artifactId}:latest</image>
					</to>
					<container>
						<mainClass>${start-class}</mainClass>
						<ports>
							<port>9090</port>
						</ports>
					</container>
					<pluginExtensions>
						<pluginExtension>
							<implementation>
								com.google.cloud.tools.jib.maven.extension.springboot.JibSpringBootExtension
							</implementation>
						</pluginExtension>
					</pluginExtensions>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.google.cloud.tools</groupId>
						<artifactId>jib-spring-boot-extension-maven</artifactId>
						<version>${jib-spring-boot-extension-maven.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>dev</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<spring.profiles.active>dev</spring.profiles.active>
			</properties>
			<dependencies>
				<dependency>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-devtools</artifactId>
					<optional>true</optional>
				</dependency>
				<dependency>
					<groupId>com.h2database</groupId>
					<artifactId>h2</artifactId>
					<scope>runtime</scope>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>prod</id>
			<properties>
				<spring.profiles.active>prod</spring.profiles.active>
			</properties>
			<dependencies>
				<dependency>
					<groupId>org.postgresql</groupId>
					<artifactId>postgresql</artifactId>
					<scope>runtime</scope>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>docker-compose</id>
			<dependencies>
				<dependency>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-docker-compose</artifactId>
					<scope>runtime</scope>
					<optional>true</optional>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>native</id>
			<properties>
				<jib-maven-plugin.image>scratch</jib-maven-plugin.image>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.hibernate.orm</groupId>
						<artifactId>hibernate-maven-plugin</artifactId>
						<version>${hibernate.version}</version>
						<executions>
							<execution>
								<id>enhance</id>
								<goals>
									<goal>enhance</goal>
								</goals>
								<configuration>
									<enableAssociationManagement>true</enableAssociationManagement>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${native-image-name}</imageName>
						</configuration>
					</plugin>
					<plugin>
						<groupId>com.google.cloud.tools</groupId>
						<artifactId>jib-maven-plugin</artifactId>
						<configuration>
							<container>
								<workingDirectory>/tmp</workingDirectory>
							</container>
							<pluginExtensions combine.self="override">
								<pluginExtension>
									<implementation>
										com.google.cloud.tools.jib.maven.extension.nativeimage.JibNativeImageExtension
									</implementation>
									<properties>
										<imageName>${native-image-name}</imageName>
									</properties>
								</pluginExtension>
							</pluginExtensions>
						</configuration>
						<dependencies>
							<dependency>
								<groupId>com.google.cloud.tools</groupId>
								<artifactId>jib-native-image-extension-maven</artifactId>
								<version>${jib-native-image-extension-maven.version}</version>
							</dependency>
						</dependencies>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>sonar</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>properties-maven-plugin</artifactId>
						<version>${properties-maven-plugin.version}</version>
						<executions>
							<execution>
								<phase>initialize</phase>
								<goals>
									<goal>read-project-properties</goal>
								</goals>
								<configuration>
									<files>
										<file>sonar-project.properties</file>
									</files>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.sonarsource.scanner.maven</groupId>
						<artifactId>sonar-maven-plugin</artifactId>
						<version>${sonar-maven-plugin.version}</version>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
