{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "spring-grpc-samples.fullname" . }}
  labels:
    {{ include "spring-grpc-samples.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "spring-grpc-samples.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- with .Values.autoscaling.behavior }}
  {{- $scaleDown := .scaleDown }}
  {{- $scaleUp := .scaleUp }}
  {{- if or (and $scaleDown $scaleDown.policies) (and $scaleUp $scaleUp.policies) }}
  behavior:
    {{- if and $scaleDown $scaleDown.policies }}
    scaleDown:
      stabilizationWindowSeconds: {{ $scaleDown.stabilizationWindowSeconds }}
      selectPolicy: {{ $scaleDown.selectPolicy }}
      policies:
        {{- toYaml $scaleDown.policies | nindent 8 }}
    {{- end }}
    {{- if and $scaleUp $scaleUp.policies }}
    scaleUp:
      stabilizationWindowSeconds: {{ $scaleUp.stabilizationWindowSeconds }}
      selectPolicy: {{ $scaleUp.selectPolicy }}
      policies:
        {{- toYaml $scaleUp.policies | nindent 8 }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
